### ISSUE TITLE
Add breathing room to top of map

### ISSUE THREAD

**Issue by ohsk** [kuanb/idbSite#1]
Could we add a bit of padding to the top of the map images? It's feeling a little cramped when there are key elements / labels at the top...

![image](https://cloud.githubusercontent.com/assets/1689222/6203933/abf81180-b506-11e4-8b82-b8ed6b8a27fb.png)

**Comment by kuanb** [comment]
done
![image](https://cloud.githubusercontent.com/assets/6053396/9504794/8f7352e8-4c0c-11e5-85f4-ed68ddb28f65.png)
